name: Push on specific branch

on: 
  push:
    branches:
      - featurex
      - develop

jobs:
  print-msg:
    runs-on: ubuntu-latest
    steps:
      - name: Say my name
        run: echo "My name is GitHub Actions"